// <auto-generated />
namespace IMSApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201709050939328_allentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
